### ISSUE TITLE
Cannot use turtles with cauldrons

### ISSUE THREAD

**Issue by IICarst** [cc-tweaked/CC-Tweaked#1008]
### Minecraft Version

1.18.x

### Version

1.100.1

### Details

I was trying to automate my dripstone lava farm but when I tried to empty a lava cauldron with a turtle it gave an error: "Cannot place item here". I used the turtle.place() function with an empty bucket selected on the cauldron.

**Comment by dathide** [comment]
I also tried this today. I think this feature should be added.

**Comment by JohnnyIrvin** [comment]
Based on https://github.com/cc-tweaked/CC-Tweaked/pull/1009#issuecomment-1172919291 --- Should we assume this issue to be closed as its not going to be implemented?

**Comment by Lupus590** [comment]
> Should we assume this issue to be closed as its not going to be implemented?

Yes, SquidDev has expressed that this is not something he wants the mod to do.
