### ISSUE TITLE
Computers are completely unfunctional

### ISSUE THREAD

**Issue by DiskMonkey** [cc-tweaked/CC-Tweaked#1012]
### Minecraft Version

1.16.x

### Version

1.99.1

### Details

Reproduced easily: open a new world and open any computer (or turtle). Instead of normal behavior, the computer outputs this screen:
![2022-01-07_20 21 35](https://user-images.githubusercontent.com/91099684/148625957-ef9c1633-e0d6-4235-a2a8-99caaae77f63.png)

In the console, the following is printed:
[onComputerOpen.txt](https://github.com/cc-tweaked/CC-Tweaked/files/7832130/onComputerOpen.txt)
![image](https://user-images.githubusercontent.com/91099684/148626069-1bb379f5-7de3-4137-a8fe-562ade33fce7.png)

Otherwise, Minecraft runs as normal, and the game does not crash completely. The player can safely ignore this issue, though using any computer is obviously impossible.

On testing, I accidentally placed a computer next to a turtle. This causes the game to immediately crash and also soft locks the world: the game crashes before it is able to load the player in. The crash log is below:
[crash-2022-01-07_20.14.25-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/7832137/crash-2022-01-07_20.14.25-server.txt)

**Comment by SquidDev** [comment]
See #972. Supplementaries is bundling the CC:T API by mistake - upgrading to their latest version should fix things.
