### ISSUE TITLE
Config file keeps being overwritten

### ISSUE THREAD

**Issue by ShockedCoder** [cc-tweaked/CC-Tweaked#1016]
### Minecraft Version

1.16.x

### Version

1.98.2

### Details

Every time I change something in the configs it resets to the default values while starting up, I tried even changing the file perms so that only root could write to it, but everyone could read from it, but it only generated an I/O error.

Log: [hastebin](https://www.toptal.com/developers/hastebin/bahoniyoxe)

**Comment by SquidDev** [comment]
Config files should only reset fields which are malformed. You should get a log message telling you what was reset and why.

**Comment by ShockedCoder** [comment]
the http.rules "$private" thingy from "deny" to "allow" that's it

**Comment by ShockedCoder** [comment]
> What config entry did you change and what value did you set it to?

the http.rules "$private" thingy from "deny" to "allow" that's it

**Comment by ShockedCoder** [comment]
it worked at first, but then it started resetting it for no reason

**Comment by ShockedCoder** [comment]
I past that anyway, I just used a roundabout way of using local servers and just used Tailscale to make it possible
