### ISSUE TITLE
Dedicated storage for library code

### ISSUE THREAD

**Issue by djmattyg007** [cc-tweaked/CC-Tweaked#1018]
I've written a bunch of common "library" code that I'd like to share between computers. Is there an easy way to do this? Right now I have to manually copy it between computers, and then I have to manually keep it up to date too.

**Comment by djmattyg007** [comment]
Even if there was no way to share it between computers, it would still be ideal if there was a dedicated path within each computer for storing this code that was automatically added to `package.path`. Right now I store it in the root folder of each computer, and add this to the top of every script:

```
package.path = "/?;/?.lua;/?/init.lua;" .. package.path
```

**Comment by Lupus590** [comment]
If you are playing singleplayer then you could create a custom datapack.

**Comment by djmattyg007** [comment]
Would you be able to expand on that? How does it work? How would I learn to do that? What makes that solution exclusive to single player?

**Comment by Toad-Dev** [comment]
https://github.com/cc-tweaked/datapack-example. The readme explains pretty much all of the how-to. It's not exclusive to single player per se, it's just that you need admin access to the multiplayer server in order to make it load a pack, which isn't always an option. Also the datapack content will affect all computers, which may not always be a great idea in multiplayer.

**Comment by absolument** [comment]
In-game solution could be to store this library on a disk, and connect every computer to the same disk drive (wired network). Put a startup on the disk which load the library. Then you can use this library on every computers, from a single file.

**Comment by djmattyg007** [comment]
I don't mind the datapack idea too much, but it isn't very dynamic. Every change would require reloading configuration in full.

**Comment by walksanatora** [comment]
i wish that package.path would be something you can edit globally and have it work globally
that or a read/writable folder that you can put libraries in that is automatically on package.path

**Comment by djmattyg007** [comment]
That is deliciously horrifying 😅
