### ISSUE TITLE
Monitor useless with shader

### ISSUE THREAD

**Issue by imstupidwithlinux** [cc-tweaked/CC-Tweaked#1020]
![Bild_2022-01-20_202518](https://user-images.githubusercontent.com/87829672/150408216-89affe35-19a0-4349-a28b-33dc5eb7b01e.png)
### Minecraft Version

1.18.x

### Version

1.100.2

### Details

im running optifine with the sildurs vibrant 1.32 extreme and as soon im using it the screens goes into this white noise mode and acts like an xray

**Comment by xAnavrins** [comment]
In CC:Tweaked's mod options, then in `Peripherals`, you need to change the `Monitor renderer` value to something that isn't `Texture Buffers` while using shaders.

**Comment by SquidDev** [comment]
See Anavrin's comment and [this wiki page](https://github.com/cc-tweaked/CC-Tweaked/wiki/Monitor-renderers).
