### ISSUE TITLE
Storage drawers push/pull items doesn't with modems

### ISSUE THREAD

**Issue by TheIncgi** [cc-tweaked/CC-Tweaked#1023]
### Minecraft Version

1.16.x

### Version

1.100.2

### Details

# Version info
### Storage Drawers 1.16.5 8.5.1
# The setup
![image](https://user-images.githubusercontent.com/30257460/150454266-c52aa2da-207c-49c1-b03a-2992d3707471.png)
(Seen left to right: computer, modem block, controller_slave, oak_trim, controller & full_drawers
  the particular arrangement here isn't important, just that there is a modem between the computer and a controller or drawer)
```lua
leftInv = peripheral.wrap"left"
sdcsName = "storagedrawers:controller_slave"
sdcs = peripheral.find(sdcsName)

if not sdcs then error("didn't wrap") end

print(textutils.serialize(peripheral.getNames()))
print(sdcs)

print("Slot 2 "..(
  textutils.serialize(sdcs.getItemDetail(2))  
))

leftInv.pullItems( sdcsName, 2 ) --line 14
```
The result
![image](https://user-images.githubusercontent.com/30257460/150455531-0c2b7c34-a23c-42c9-85e7-c5c41e544be9.png)

We can see that items can be inspected fine however it causes an error when pushing or pulling items

# Second test: without a modem
![image](https://user-images.githubusercontent.com/30257460/150454504-2f060c9e-05aa-4c9f-8ba9-ffd07e0b9df3.png)
the 2nd and 3rd lines are changed to this:
```lua
sdcsName = "back"
sdcs = peripheral.wrap(sdcsName)
```
![image](https://user-images.githubusercontent.com/30257460/150457323-3fc5d786-16d6-4eda-a7a9-b210eb858af0.png)

## The item is transferred successfully 
![image](https://user-images.githubusercontent.com/30257460/150455265-12785922-c7bf-471b-96e7-7706d22a1b99.png)

-------------
# Additional note:
I tried to see if I could setup a dev workspace to find the cause of the issue myself, I was able to get CC-Tweaked to run in debug mode, however I couldn't figure out how to get Storage drawers to load in without causing a crash on startup. If you have any tips I can try and find the issue and PR, although it may be a simple enough fix that it's not worth me trying.

**Comment by Wojbie** [comment]
Duplicate of #697

Please red there to get explanation why it works this way. TLDR: it's way CC networks work.

**Comment by TheIncgi** [comment]
Ah
I looked though open issues and missed this. 
This picture alone gives me a good idea of what's going on, but I'll read the page too.

Thanks for your help.
