### ISSUE TITLE
Disk Drives with NBT capabilities

### ISSUE THREAD

**Issue by Donovan2649** [cc-tweaked/CC-Tweaked#1024]
Disk drives currently in CC can play vanilla or modded music disks but it currently cannot play music disks added from data packs. If the disks were to read the NBT tags it would be cool if it played them too.

**Comment by MCJack123** [comment]
Please show an example of the data pack you're trying to use. It appears the ones I'm finding use `playsound` on a jukebox in a function, and the actual data of the disc has nothing to do with the actual sound played. However, there could be some new feature that I'm missing or misunderstanding.

**Comment by SquidDev** [comment]
As Jack says, there's not not enough information to do anything here.
