### ISSUE TITLE
Can't equip tools to turtles

### ISSUE THREAD

**Issue by DataTriny** [cc-tweaked/CC-Tweaked#1025]
### Minecraft Version

1.18.x

### Version

CC: Tweaked 1.100.2, Forge 39.0.59

#### Steps to reproduce

1. Place a Turtle or an Advanced turtle,
2. Put a tool from Minecraft Vanilla in the first inventory slot (I tried axes, pickaxes and shovels of different materials),
3. Open the Lua REPL,
4. Call `turtle.equipLeft()` (I get the same behavior with `equipRight`,
5. `false, "Not a valid upgrade"` is returned.

Trying to directly craft a turtle with a tool does not work either, nothing gets crafted. However I can equip a Wireless Modem just fine.

#### Logs

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/7921127/latest.log)

[debug.log](https://github.com/cc-tweaked/CC-Tweaked/files/7921131/debug.log)

**Comment by SquidDev** [comment]
![A screenshot of a ComputerCraft turtle, with a diamond pickaxe in slot 1. The terminal has the Lua REPL open, demonstrating that turtle.equipLeft and turtle.equipRight return true](https://user-images.githubusercontent.com/4346137/150698091-84172df7-f44d-4c6f-8a93-5b5ca6f52054.png)

It appears to work for me. Just to confirm, the pickaxe is a new one, and hasn't been damaged, renamed or enchanted in any way?

**Comment by DataTriny** [comment]
@SquidDev  the tools I tested came straight from the Creative inventory (not damaged, not renamed, not enchanted).

I can see a bunch of exceptions in the debug log but nothing very helpful...

I am running Ubuntu 20.04 by the way.

**Comment by Lupus590** [comment]
Astral Sorcery changes new tools and *used to* break CC:T's tool equipping, perhaps there is another mod doing that now.

Try to reproduce the bug with just CCLT installed, if it works as expected then install mods one at a time to narrow down which is conflicting.

**Comment by DataTriny** [comment]
I initially tried on a Forge profile with other mods but reproduced the issue on a fresh one before reporting here. Do config/resource files managed by Forge get regenerated at each game startup, or should I delete some cache files that might have been kept from the old profile?

**Comment by Wojbie** [comment]
Have you been testing on clean world+new pickaxe each time? If pickaxe was modified by some mod then tags will stay on that pickaxe after you removed the mod.

Here is other test: put pickaxe in your hand slot and type `/data get entity @s SelectedItem` . Is your output different from mine? If so can you share it?
![obraz](https://user-images.githubusercontent.com/5893536/150704343-c9e07800-0dcb-479a-b6f8-d6db7f394c0a.png)

**Comment by DataTriny** [comment]
@Wojbie I have performed all the tests on a new world that I created when I had only CC: Tweaked installed and all the tools were brand new. Issuing the command you gave outputs the same result on my side.

Now, taking a more systematic approach by testing all possible tools revealed something interesting: I can equip any tool made out of diamond, but nothing else. Since you guys have only showed me results with diamond tools, would you mind trying with tools made of something else than diamond?

**Comment by DataTriny** [comment]
I missed that. Coming from OpenComputers and I didn't remember this detail from the old ComputerCraft. Sorry for wasting your time.
Thanks.
