### ISSUE TITLE
How about Add Edu Turtle in this Mod !XD

### ISSUE THREAD

**Issue by fan9704** [cc-tweaked/CC-Tweaked#1031]
## Useful information to include:
 - Explanation of how the feature/change should work.
 - Some rationale/use case for a feature. My general approach to designing new features is to ask yourself "what issue are we trying to solve" and _then_ "is this the best way to solve this issue?".

**Comment by Lupus590** [comment]
related/duplicate: https://github.com/dan200/ComputerCraft/issues/606

**Comment by SquidDev** [comment]
Also #784.
