### ISSUE TITLE
Another monitor render bug

### ISSUE THREAD

**Issue by Shinnonda** [cc-tweaked/CC-Tweaked#1033]
### Minecraft Version

1.16.x

### Version

1.16.5-1.100.2

### Details

![Screenshot_2022-02-01_231037](https://user-images.githubusercontent.com/13296176/152143656-57efa4a6-7e3f-4db7-92fb-94c22b89ad73.png)

For some reason the monitors are completly transparent in most of the angles i can look at them (when i'm looking from above it almost work all the time). I did tried all 3 renderer options via config file, and redo the test after fully closing the game and creating a new map (just in case) but i can't figure what is causing it.

I'm not using Optifine or shaders, this modpack is basically "Better Minecraft modpack" but without Magnesium and Dynamic Lights (which i removed thinking it may be the reason the problem is happening, as far i looked, those are the only mods related to rendering changes on the game). I also started to poke out all the other mods one by one to see if it was related to other mods, but the issue still happening. I just don't know what is causing it...

**Comment by Lupus590** [comment]
Extra info that can be helpful:
 * Java version that MC is using (you can find this in your launcher)
 * GPU that you have

Another thing to check would be if the problem persists with just CC:T installed.

**Comment by Shinnonda** [comment]
Java 1.8.0_51 64 bits
GPU: RX590 8GB

I tried by itself eventually since i was removing mods one by one while trying to figure whats causing it, still having the issue anyways.
An previous version i used 2 months ago was working fine with the same mods (also in older versions of them) and by itself, no render issues.

**Comment by Shinnonda** [comment]
Ok, after some new testing i think i figure out what the problem was, the mod "entity culling" can't detect that the monitor screen is a visible face of the block (maybe cause it detects as hidden behind the front face of the block that is transparent but not like glass, which is ignored by the culling detection), i had removed the mod but it looks like some of the settings from it was stucked somehow on the game, so i basically hunt all files related to it and the issue vanished. Is working perfectly now.
