### ISSUE TITLE
about minecraft 1.18

### ISSUE THREAD

**Issue by mastertarreria** [cc-tweaked/CC-Tweaked#1036]
### Minecraft Version

1.18.x

### Version

cc-tweaked-1.18-1.99.0.jar

### Details

ive tryed everything extracting getting computercraft and extracting it also but no matter what i can not make cc tweaked work in exactly 1.18 please fix this its on curseforge

**Comment by xAnavrins** [comment]
Your issue is very vague...
Two things, if you're having trouble getting a mod to run on your launcher, this isn't really the place to get help from.
If you did get CC:T to work but it's still causing issues, please try with latest release that's on Curseforge, which is `1.100.2`, and not `1.99.0`

**Comment by SquidDev** [comment]
As xAnavrins says, please update to update to 1.18.1 and the latest version of the mod. There shouldn't be any reason to run minor versions of the game.

**Comment by lokilost1** [comment]
ok thanks the thing is mods can run but i cant see they recipies with jei and i have other mod but i will try
