### ISSUE TITLE
`rednet.lookup` is returning nil (`chat` program has stopped working)

### ISSUE THREAD

**Issue by Cheatoid** [cc-tweaked/CC-Tweaked#1037]
### Minecraft Version

1.18.x

### Version

1.100.2

### Details

As the title says.
Simplest way to reproduce this issue is to make use of the `chat` program.
Place down a computer with modem on side, access the terminal and enter `chat host room`.
Place down another computer with modem on side, access the terminal and enter `chat join room username`, and then here you will see the issue:
> Looking up room... Failed.

**Comment by Wojbie** [comment]
I can't seem to replicate your issue. Did exactly what your steps were and it worked correctly. Can you provide screenshots of your setup/other details or save file with this issue in action? 
![obraz](https://user-images.githubusercontent.com/5893536/153726807-e7f22907-668b-49a6-876a-8379bf5e08d6.png)
![obraz](https://user-images.githubusercontent.com/5893536/153726811-7c7e5079-8b6b-4ef1-b66e-6e70a0d39a12.png)

**Comment by Cheatoid** [comment]
Well this is strange. It does not work in this particular setup which I have here, not sure why.
I just tested it again by placing a new set of computers and it works fine.

Video demo: https://streamable.com/udq3zy

**Comment by Cheatoid** [comment]
I think I figured it out. It is because both computers have the identical metadata/ID, so it ends up failing during lookup... 😆
This is so silly. It is easy to get multiple computers with identical ID while in creative, simply destroy a computer after placing it, and then middle click it on hotbar.

**Comment by Wojbie** [comment]
> I think I figured it out. It is because both computers have the identical metadata/ID, so it ends up failing during lookup... 😆 This is so silly. It is easy to get multiple computers with identical ID while in creative, simply destroy a computer after placing it, and then middle click it on hotbar.

It is working like that on purpose. Cause if computer sends message to itself (its own ID) it is just queued as event and it allows multiple programs on same computer to communicate over rednet without actually having any modems on the computer cause it is all in effect loopback communication. https://github.com/cc-tweaked/CC-Tweaked/blob/cdf8b77ffd20460cc59670b4f9052f43672e6b1e/src/main/resources/data/computercraft/lua/rom/apis/rednet.lua#L194-L198

So if there are multiple computers with same ID they are unable to communicate with each other cause of said ID collision. Lucky it can't happen in normal game play.
