### ISSUE TITLE
Minecraft crashed after placing a computer

### ISSUE THREAD

**Issue by daniel007boss** [cc-tweaked/CC-Tweaked#1039]
### Minecraft Version

1.16.x

### Version

1.100.2

### Details

after putting a computer in front of a reinforced computer port of big reactor the game crashed, i tried to reload the modpack and launch the game again and crashed again with this message:

The game crashed whilst ticking block entity
Error: java.lang.NoSuchMethodError: dan200.computercraft.api.peripheral.IPeripheral.getAdditionalTypes()Ljava/util/Set;
Codice di uscita: -1

[crash-2022-02-13_17.38.18-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/8056111/crash-2022-02-13_17.38.18-server.txt)
here the crash report i'v no idea what happened

**Comment by SquidDev** [comment]
See #972. Please update Supplementaries to the latest version.
