### ISSUE TITLE
Auto Chisel & CC-Tweaked Turtle Crash - Can't reload map

### ISSUE THREAD

**Issue by TheIncgi** [cc-tweaked/CC-Tweaked#1041]
### Minecraft Version

1.16.x

### Version

1.100.2

### Details

# mc 1.16.5
# cc-tweaked 1.100.2
![2022-02-14_22 29 26](https://user-images.githubusercontent.com/30257460/153987483-dcb86b36-a21f-4387-9052-b6f0ecc73d94.png)
[In a fresh creative world, Auto chisel on the left from the chisel mod and a cc-tweaked turtle near it]

with some fuel, `go forward 2`, or just place it next to it

map won't load, crashes
https://pastebin.com/kGMpJdKj

Cross posting to chisel issues since I'm not sure which mod causes the crash

Thanks in advanced for taking the time to read this

**Comment by TheIncgi** [comment]
[chisel issue link](https://github.com/Chisel-Team/Chisel/issues/920)

**Comment by SquidDev** [comment]
This appears to be a Chisel bug. Will let them handle it :).
