### ISSUE TITLE
Ender chest not detected as peripheral

### ISSUE THREAD

**Issue by antoinets** [cc-tweaked/CC-Tweaked#1042]
### Minecraft Version

1.16.5

### Version

- Forge 36.2.20
- CC: Tweaked 1.100.2

### Details

Placing a vanilla ender chest next to a computer and running:

```
peripheral.getNames()
```

returns `{}`. Using a regular chest produces eg. `{"left"}` as I expected.

Here are the [logs](https://github.com/cc-tweaked/CC-Tweaked/files/8102077/latest.log). I've reproduced this with only CC: Tweaked and no other mods installed.

**Comment by SquidDev** [comment]
I'm afraid this is expected behaviour. Ender chests don't function as inventories (for instance you can't pipe into them with hoppers), and so CC doesn't think you can do anything with them.
