### ISSUE TITLE
can't craft anything

### ISSUE THREAD

**Issue by MRMidgey** [cc-tweaked/CC-Tweaked#1045]
### Minecraft Version

1.18.x

### Version

1.100.3

### Details

can't craft anything in crafting table or inventory crafting

**Comment by xAnavrins** [comment]
What can't you craft, CC items like Computers / Turtles?, are you using orther mods, or a modpack, more context please?!

**Comment by MRMidgey** [comment]
everything from vanilla Minecraft like pickaxe and other stuff and yes I use other mods with CC

**Comment by MRMidgey** [comment]
it was a different mod fallingtree now everything works as normal sorry for the inconvenience
