### ISSUE TITLE
Mining Turtles destroying majority of items dug with turtle.dig

### ISSUE THREAD

**Issue by randomsteve95370** [cc-tweaked/CC-Tweaked#1046]
### Minecraft Version

1.18.x

### Version

1.100.2

### Details

Mining Turtles using the turtle.dig() command only rarely receive the block they mined into their inventory. Majority of blocks are destroyed. 

I noticed that my the yields from my quarry program seemed off. Watching the turtles dig they mine through blocks and ores no problem but rarely are they going into their inventories. 

I crafted a fresh mining turtle on used the lua shell to manually run some turtle.dig() commands while placing blocks in front of the turtle and he always breaks the ore and outputs a true Boolean but almost never actually gets any items in his inventory. After going through a full stack of ore he had only a few iron in his inventory all the rest was simply gone. I've also tried with the build in tunnel program and it correctly reports back how many blocks were mined  but almost none of them end up in the inventory. I've tested all sorts of blocks as well, ores, stone, dirt, modded blocks, vanilla blocks. Its all pretty much the same. The very first one mined of a type of block gets picked up and then the vast majority of the rest are just destroyed. 

reproduction steps. 

Minecraft 1.18.1
CC Tweaked 1.100.2

Place a mining turtle
place a block in front of the mining turtle
run turtle.dig()
repeat multiple times and check to see if the blocks in the turtles inventory add up.

**Comment by Lupus590** [comment]
Do you have any mods installed that modify how tools (especially pickaxes) work?

**Comment by SquidDev** [comment]
I was unable to reproduce this on MC 1.18.2, Forge 40.0.2 and CC:T 1.100.3. Place and broke a mixture diamond and iron ore, stone, cobblestone. Would be useful to have your logs and mod list.

**Comment by randomsteve95370** [comment]
> Do you have any mods installed that modify how tools (especially pickaxes) work?

The only thing I can think of would be Silent tools. Im not sure what all it does to the way that tools work other than adding its own versions.




> I was unable to reproduce this on MC 1.18.2, Forge 40.0.2 and CC:T 1.100.3. Place and broke a mixture diamond and iron ore, stone, cobblestone. Would be useful to have your logs and mod list.

When I get back to the computer I will pull up a log and mods list to post on here. I am really interested to know what interaction might be causing this issue.

**Comment by randomsteve95370** [comment]
Here is the latest Log file 

https://pastebin.com/RKEWvpGD

**Comment by SquidDev** [comment]
I think it's worth [reporting this on their repo](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/issues/new/choose) - I'd guess something in their code is interfering with [CC:T's `DropConsumer`](https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.16.x/src/main/java/dan200/computercraft/shared/util/DropConsumer.java).

Probably worth doing this first:
 - Run `/aptweaks debug true`
 - Break some blocks with the turtle
 - Include your debug.log in the bug report.
