### ISSUE TITLE
Allow accessing inventories of minecarts.

### ISSUE THREAD

**Issue by GlowingUmbreon** [cc-tweaked/CC-Tweaked#1048]
Currently it is not possible to access the inventories of minecarts, one possible way this could be implemented is to have a detector rail next to the computer and if a minecart that contains a inventory is over the rail then you can access the inventory for it as you would with other inventories.

**Comment by mcenderdragon** [comment]
another Method could be a block that redirekts all getCapabiltiy calls to the entity standing at a specific side. THis way alot of other stuff could be supported.

**Comment by SquidDev** [comment]
I think this is a neat idea for a peripheral mod, but not something I want to add to CC. It should be possible to `turtle.drop`/`turtle.suck` into a minecart, but that's as far as I want to go.
