### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraftforge/event/RegistryEvent$NewRegistry

### ISSUE THREAD

**Issue by MLDKYT** [cc-tweaked/CC-Tweaked#1052]
### Minecraft Version

1.18.x

### Version

1.100.3

### Details

![Screenshot_20220321_161536](https://user-images.githubusercontent.com/59791284/159292646-9069484e-bf45-427a-a7d9-1c48e23540c1.png)
[log.log](https://github.com/cc-tweaked/CC-Tweaked/files/8316617/log.log)

**Comment by MLDKYT** [comment]
[crash-2022-03-21_16.15.12-fml.txt](https://github.com/cc-tweaked/CC-Tweaked/files/8316625/crash-2022-03-21_16.15.12-fml.txt)

**Comment by SquidDev** [comment]
#1049.
