### ISSUE TITLE
crash on startup version 40.0.18 of forge 1.18.2

### ISSUE THREAD

**Issue by WelpSTudent** [cc-tweaked/CC-Tweaked#1054]
### Minecraft Version

1.18.x

### Version

1.100.3

### Details

crash on startup version 40.0.18 of forge 1.18.2
https://pastebin.com/yGjrZyc7

**Comment by SquidDev** [comment]
#1049

**Comment by WelpSTudent** [comment]
With latest patch, 1.100.4, it still crashes
https://gist.github.com/WelpSTudent/811679ea983dffac93d88bd68ab4af6e
