### ISSUE TITLE
Block Setup Documentation - ingame or on website

### ISSUE THREAD

**Issue by LordHelmchen** [cc-tweaked/CC-Tweaked#1068]
I was missing some basic block guides. The programming API is well documented, but without knowing what to look for it took quite a while to find out, that I have to right click a modem for it to work. I simply didn't understand why modems would not do anything or if I have to write messages or do remote calls on the modem or if I have to set up a computer next to each inventory/peripheral I want to modify.

https://github.com/cc-tweaked/CC-Tweaked/issues/1023#issuecomment-1018125204 has picture that explained basic networking and made sure, that I was on the right track. In the mentioned issue the modems were red, which was different from mine.

After I found out about it, I looked for someone else mentioning it:
http://www.computercraft.info/forums2/index.php?/topic/11244-151-using-network-cables-for-dummies/ is a small example that mentions this important fact.

A small block setup + wrap peripheral + transfer item example would make it much easier to understand how CC works in general.

**Comment by Lupus590** [comment]
Adding to this, an example GPS setup would also be useful.

The documentation system does support wiki/guide like entries (got to tweaked.cc and scroll the index to the bottom), so one just needs to make a PR assign a new file to https://github.com/cc-tweaked/CC-Tweaked/tree/mc-1.16.x/doc/guides. Just a note that legally we can't copy from the old wikis, so someone who already knows how to do some of this stuff would have to write it.

**Comment by Lupus590** [comment]
Going to try to make a couple of PRs covering this kind of stuff. It's probably going to take me a while though.

**Comment by Lupus590** [comment]
What I'm currently writing:
* using startup files
* setting up GPS
* using modems for communication and connecting peripherals

I might do these as separate PRs

**Comment by SquidDev** [comment]
Worth mentioning that there's _some_ stuff about monitors in the [introduction to the `peripheral` API](https://tweaked.cc/module/peripheral.html), but it's not great - could probably do with fleshing out or cross-referencing with other pages.
