### ISSUE TITLE
Type in colors API

### ISSUE THREAD

**Issue by PlexifyUwU** [cc-tweaked/CC-Tweaked#1072]
There is a typo in file "https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.16.x/src/main/resources/data/computercraft/lua/rom/apis/colors.lua" Where the green channels on lines "271", "294" respectively are shown to be "The red channel" instead of "The green channel"
This is a minor bug and wont take long to fix, Farewell!

**Comment by SquidDev** [comment]
Good spot! Thank you.
