### ISSUE TITLE
Add RF/FE charger for turtles.

### ISSUE THREAD

**Issue by DVD-DAVIDE** [cc-tweaked/CC-Tweaked#1073]
I'd like to suggest an idea for an addition to cc.
A way to convert Forge Energy (or Redstone Flux, etc...) into turtle fuel.
The main reason for this would simply be that coal is not renewable nor infinite.
This would solve the problem in a rather simple way (I'm talking about use, I don't know about implementation)
It could be added as a "native" turtle api or as a new peripheral.
It doesn't have to be extremely powerful, it could just have a 10 (or even 100) FE to 1 fuel rate. Maybe getting more efficient on advanced turtles (or maybe not, since they already use half of the fuel to move).
I would maybe add this myself (maybe in another mod), but I wouldn't even know where to start.

**Comment by SquidDev** [comment]
> The main reason for this would simply be that coal is not renewable nor infinite.

Worth nothing that turtles accept any furnace fuel, and most of these are renewable (charcoal, bamboo, lava, blaze rods). Personally I find it more interesting to automate one of those than resorting to FE.

**Comment by DVD-DAVIDE** [comment]
Oh, well, you're right.
Btw (don't wanna make a new issue just about that), what about allowing turtles equip netherite picks, too?

**Comment by Lupus590** [comment]
> what about allowing turtles equip netherite picks, too?

Data packs and crafttwraker depending on mc version cam do this.

**Comment by DVD-DAVIDE** [comment]
I thought it would be possible, but it'd be nice to have it by default.
Also diamond enchanted tools can't be equipped.

**Comment by Lupus590** [comment]
You might be able to do enchanted tools with the same method. I've not used either so I don't know, I just know that it exists and can allow other tools.

**Comment by SirEdvin** [comment]
@Lupus590, and enchantments will be propagated? 

@DVD-DAVIDE, btw, Advanced Peripherals allow something like this https://docs.srendi.de/1.18/metaphysics/weak_automata/ with `chargeTurtle` method

**Comment by DVD-DAVIDE** [comment]
@SirEdvin thank you for the info.
I really hadn't seen it and thought it wasn't possible.
Anyways, I think I'm gonna close this issue, since the matter is resolved.

**Comment by Lupus590** [comment]
> @Lupus590, and enchantments will be propagated? 

@SirEdvin no idea
