### ISSUE TITLE
Monitor rendering bug

### ISSUE THREAD

**Issue by Niall-mc** [cc-tweaked/CC-Tweaked#1077]
### Minecraft Version

1.16.x

### Version

1.100.4

### Details

When I leave the area and return the program has condensed into the bottom left monitor and the rest of the monitor becomes transparent.

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/8534177/latest.log)
![2022-04-20_21 59 03](https://user-images.githubusercontent.com/50273089/164530055-5f53a5c9-420e-40bb-a95c-89b1e4f4bc67.png)

**Comment by Lupus590** [comment]
Do you have any shader mods? If yes then either disable your shaders or switch to the vbo renderer in computercrafts client side config.

**Comment by Niall-mc** [comment]
No shader mods, I did try setting it to VBO anyway but it didn't help

**Comment by Lupus590** [comment]
Can you give a mod list?

**Comment by Niall-mc** [comment]
https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond with updated forge and cc

**Comment by SquidDev** [comment]
Yeah, if this only happens when revisiting after being away for a while, it's probably not a optifine compatibility issue and an issue elsewhere.

It's odd - the terminal contents is being synced to the client, but it's almost like the monitor's size is wrong. This _might_ be introduced in 31ba17d0856b809ed71291323be06e89046f6edd - you could try rolling back to 1.100.3 and see if it helps.

**Comment by Niall-mc** [comment]
Issue still there on 1.100.3

**Comment by SquidDev** [comment]
When this next occurs, can you take a look at the four corner monitors in F3/debug mode and post the `Targeted Monitor: ` values for each.

![A screenshot of Minecraft's F3 debug screen with the "Targeted Monitor:" section highlighted](https://user-images.githubusercontent.com/4346137/164968572-120dc2a5-84be-4c6e-980f-016a278e9f25.png)


I've not been able to reproduce this locally, so just having an idea of what might be going on would be very useful.

**Comment by Niall-mc** [comment]
It says "Targeted monitor: (0, 0), 1 x 1" when I look at every monitor in the 3 x 3
![tmon](https://user-images.githubusercontent.com/50273089/165186330-db34dc1a-8103-4967-b534-07044be93750.png)

**Comment by Niall-mc** [comment]
Removing the stasis blocks fixes the issue. Updated More Minecarts and they still cause it so I'll send a report their way. Thanks Squid.

**Comment by SquidDev** [comment]
Wonderful! I'm going to close this as I don't think there's anything left on my end. Happy to reopen if it does crop up again.
