### ISSUE TITLE
Add CJK characters support in terminal

### ISSUE THREAD

**Issue by shs3182ym** [cc-tweaked/CC-Tweaked#1081]
Please add CJK characers (Hangul, Hiragana, Katakana, Kanji, etc...) support in terminal.

(Sorry I can't use English well.)

**Comment by SquidDev** [comment]
There's been some discussion about this before in #860. I'd definitely love to see it in CC:T, but was never able to work out an API which wouldn't end up a little messy.

I'm afraid I view CC:T as "feature complete" at this point, and so this won't be added to this mod. Hopefully a fork will eventually arise which is able to figure something out.
