### ISSUE TITLE
CC Blocks do not rotate in structures

### ISSUE THREAD

**Issue by Seniorendi** [cc-tweaked/CC-Tweaked#1082]
### Minecraft Version

1.16.x

### Version

1.100.5

### Details

I have this problem also for 1.18

I use blocks from CC:T for my structures in AP. But they don't rotate when the feature is placed. 
The block classes([BlockComputer](https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.16.x/src/main/java/dan200/computercraft/shared/computer/blocks/BlockComputer.java) for example) do not override the `mirror` method, so they don't rotate. See [here](https://github.com/Seniorendi/AdvancedPeripherals/issues/284) for context

**Comment by Seniorendi** [comment]
![image](https://user-images.githubusercontent.com/67484093/166107778-4daf02f9-6892-4b8d-99da-4917ecc97abd.png)
👀 
approved

**Comment by SquidDev** [comment]
You know you want that sweet "Contributor" badge!
