### ISSUE TITLE
Dance command in turtle crashes game and bricks world

### ISSUE THREAD

**Issue by Kickbub** [cc-tweaked/CC-Tweaked#1087]
### Minecraft Version

1.16.x

### Version

1.99.0

### Details

Typing the `dance` command into a turtle will crash the game and make the world unusable until the turtle is deleted with MCedit.

[crash-2022-05-04_16.14.45-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/8627976/crash-2022-05-04_16.14.45-server.txt)

**Comment by SquidDev** [comment]
See #972. Please update Supplementaries to the latest version.
