### ISSUE TITLE
Properly dithered audio sounds like hot garbage when played through a speaker

### ISSUE THREAD

**Issue by Zipdox** [cc-tweaked/CC-Tweaked#1229]
### Minecraft Version

1.19.x

### Version

1.101.1

### Details

Get an advanced computer, disk drive with a floppy disk and a speaker and place them next to each other.

Put [this file](https://files.catbox.moe/ttjuon.pcm) on the floppy disk and name it `audio.pcm`.  You'll probably have to increase the max floppy disk size.

Run this code:

```lua
local speaker = peripheral.find("speaker")
local pcmfile = io.open("disk/audio.pcm", "rb")
local chunksize = 4800
local samples_played = 0

while true do
    local chunk = pcmfile:read(chunksize)
    if not chunk then break end
    samples_played = samples_played + chunksize
    local audiobuffer = {}
    for i = 1, string.len(chunk), 1
    do
        audiobuffer[i] = string.byte(chunk, i) - 128
    end
    while not speaker.playAudio(audiobuffer) do
        os.pullEvent("speaker_audio_empty")
    end
    local timeMinutes = math.floor(samples_played / 2880000)
    local timeSeconds = math.floor((samples_played / 48000) % 60)
    local timeDecimal = (samples_played / chunksize) % 10
    local timeString = string.format("%d:%02d.%d\n", timeMinutes, timeSeconds, timeDecimal)
    term.clear()
    print(timeString)
end
```

It sounds way too crunchy. As a comparison [here](https://files.catbox.moe/rktcry.wav) is the same PCM data packaged in a WAV file. It sounds much better (though obviously noise due to 8 bit samples).

So why is this. Is the audio being re-encoded to DFPWM on the fly? If so, why not use a real low latency codec like Opus to do this? Opus can achieve full stereo transparency at 64kbps.

**Comment by Wojbie** [comment]
> Is the audio being re-encoded to DFPWM on the fly?

Yes. CC:T uses DFPWM to transfer audio from server to clients internally on java side. You can't avoid your audio going thru this process.

**Comment by Lemmmy** [comment]
> Opus can achieve full stereo transparency at 64kbps.

This may be true for a single stream, but quickly falls apart when you have a server with multiple speakers running at once. You effectively become an audio streaming service, and that bandwidth isn't cheap.

**Comment by Zipdox** [comment]
Opus is superior to DFPWM in terms of bandwidth saving. DFPWM is 1 bit per sample. At 48KHz sample rate that is 48kbps. Opus sounds way better than DFPWM at that bitrate.

> legacy support

A server won't permit you to join unless the mod versions match, so I don't get this point. If you're talking about code compatibility, you could add a new function instead of reworking the old one.

> To give a more practical comparison, along with a real-world use case, take these theoretical numbers. 8 speakers playing different audio streams at 64 Kbps each is 0.5 Mbps of audio.

Simply choose a lower bitrate. It'll still sound better than DFPWM. 32kbps still sounds good on mono. 16kbps is acceptable too. This is less than the bitrate of DFPWM. Obviously the bitrate should be configurable. You could also encode multiple channels into a single multi-channel bitstream, which permits joint encoding for lower overhead, although implementing this is probably a bit complicated.

> Broadcast that to 10 players online, and you've already saturated a "good" home ADSL Broadband upload. 20 players and you've exceeded the [average upload speed of a UK home](https://www.broadband.co.uk/pressreleases/uk-broadband-speeds-january-2021.pdf).

Why the hell would you host a server for 20 players on an ADSL connection? Especially a modded server? Such a server would crap out before you even use a speaker.

**Comment by SquidDev** [comment]
Yep, this is working as intended! The slightly janky audio compression artifacts was an intentional aesthetic choice.

**Comment by Zipdox** [comment]
So are you open to pull requests?

**Comment by SquidDev** [comment]
In general? Definitely! Changing the audio encoding used, probably not.

**Comment by Kan18** [comment]
Could there be an alternative option to pass DFPWM directly to the speaker peripheral? It seems somewhat wasteful if a CC computer downloads DFPWM audio from somewhere, decodes it to PCM, and then passes it to the speaker where it is just encoded back to DFPWM - the decode and encode steps on a server could just be entirely skipped

**Comment by Zipdox** [comment]
> Could there be an alternative option to pass DFPWM directly to the speaker peripheral? It seems somewhat wasteful if a CC computer downloads DFPWM audio from somewhere, decodes it to PCM, and then passes it to the speaker where it is just encoded back to DFPWM - the decode and encode steps on a server could just be entirely skipped

Oh crap yeah I just noticed there's no way to play already encoded DFPWM. I guess you could encode audio yourself with a better codec though.
