### ISSUE TITLE
Turtles can't place buckets into Ender Tanks.

### ISSUE THREAD

**Issue by ghost** [cc-tweaked/CC-Tweaked#345]
- MC 1.12.2
 - CC:T version 1.86.0

Turtles cannot place buckets into Ender Tanks from the Ender Storage mod, from any side.

**Comment by Kaikaku** [comment]
I'd like to add some further info to the topic of turtles beeing unable to place fluids in tanks. However, I'm talking about 
MC 1.16 with CC:Tweaked 1.16.4, 1.95.2 (mod pack Direwolf20 1.16, 1.7).

Turtles seem generally not beeing able to interact with fluid tanks (using a bucket): Holds true for 
1) vanilla water
2) moded liquids like pneumaticcraft:oil that can be placed in the world
3) liquids that can't be placed in the world like minecraft:milk

Lets assume a tank in front of the turtle and the turtle tries to turtle.place() a bucket with liquid:

A) Placing liquids:
a) In case of water (1) the turtle first water-locks itself.
b) Then, if there is a block below the tank, the liquid (1+2) is placed above the tank.
c) If not b) than the turtle places the fluid behind the tank
After b/c the turtle begins to destroy liquid by placing it in the same space.

B) Getting liquids:
Turtles can't get liquids from tanks.
If the turtle is water-locked, it takes this water.

All in all a strange behavior, partly similar like placing fluids by hand holding shift.

**Comment by Lupus590** [comment]
I would kinda expect the drop and suck functions to work for placing/taking buckets of liquid into/from tanks. As far as I know, the stuff isn't supported and I've written a program that uses a Railcraft fluid cart loader as a workaround to this.

**Comment by SquidDev** [comment]
Hopefully fixed by 118d04f018923ccb850a005c082688e60959df27, though would need some additional customisation in a datapack.
