### ISSUE TITLE
global network proxy

### ISSUE THREAD

**Issue by chenxuuu** [cc-tweaked/CC-Tweaked#369]
sometimes such as `raw.githubusercontent.com`, can't be connected in China, many install scripts use this
If computer have commands like `setproxy http://127.0.0.1:1080` or `setproxy socks://127.0.0.1:1080`, it will be useful when connect github and download scripts.

![图片](https://user-images.githubusercontent.com/10357394/74096136-b3cb0c80-4b35-11ea-9815-4a1e501c5c16.png)

**Comment by Lustyn** [comment]
[Standard Java proxy settings](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html) *should* allow you to set a proxy when starting the Minecraft client or server.

**Comment by chenxuuu** [comment]
@Lustyn not means all server data through proxy, just cc mod's.

**Comment by lupus590** [comment]
Feels like something which should be done in the config file
