### ISSUE TITLE
[1.16.4] Turtle can't place Traveler's Backpacks

### ISSUE THREAD

**Issue by Flexico** [cc-tweaked/CC-Tweaked#654]
MC 1.16.4
Forge 35.1.29
CC Tweaked 1.95.0
Traveler's Backpack 5.3.3

Traveler's Backpacks can both be worn and placed on the ground, but placing it requires holding Shift, so that may have something to do with why a turtle can't place it. I get the error, "Cannot place block here."

**Comment by Flexico** [comment]
Update: Still doesn't work on MC 1.16.5 / Forge 36.0.15 / CCT 1.95.2

**Comment by SquidDev** [comment]
This should work as of 2e5cd29e12db67c925c4ce5bd114c62d1bbae438.
