### ISSUE TITLE
Peripheral reports invalid size of chest on 1.16.4 in some cases.

### ISSUE THREAD

**Issue by Wojbie** [cc-tweaked/CC-Tweaked#696]
Reproduction:
Prep: Place a computer/turtle on left. Place a block to side (grass in image) of it.
1. Place a chest on top of the block.
2. Shift r-click chest on the side of existing chest to create double chest. (or place is without shift by clicking on normal block - same effect.)
3. Peripheral will show a single chest with 27 slots instead of double sized 54. (green frame)

Placing chest on top of computer first and then shift clicking on side of it to place one above grass will create double chest that does not show as peripheral until turtle rotates. (red frame) I was unable to make it "appear" for normal computer.
When doing the testing i was able to sometimes get proper 54 sized chest peripheral.

When testing with full block modems modems in place of computer i was able to cause all 3 states to happen but was unable to pin down reproduction steps for them.

I believe it might be related to changed chest placing logic in newer versions.
![obraz](https://user-images.githubusercontent.com/5893536/105728839-dfa0f700-5f2c-11eb-9c68-7203de19be6a.png)
![obraz](https://user-images.githubusercontent.com/5893536/105729558-a917ac00-5f2d-11eb-9bc0-8d84a8976064.png)
![obraz](https://user-images.githubusercontent.com/5893536/105729740-d19fa600-5f2d-11eb-9864-9898f389f3c4.png)

 - Minecraft version: 1.16.4
 - CC: Tweaked version: 1.95.2
 - Forge version: 35.1.36
 
 Probably unrelated but the fact that there is no peripheral case reminds me of #660

**Comment by Ronan-H** [comment]
Was able to reproduce the two bugged scenarios in:
- MC 1.15.2
- CC 1.95.3

> Probably unrelated but the fact that there is no peripheral case reminds me of #660

If #743 is accepted as a working fix then it's unrelated for sure.
