### ISSUE TITLE
Update to Lua 5.2

### ISSUE THREAD

**Issue by SquidDev** [cc-tweaked/CC-Tweaked#768]
As mentioned in [this discussion](https://github.com/SquidDev-CC/CC-Tweaked/discussions/757), there's been some fantastic work to update CC:T to Lua 5.2.

Obviously we want to get these changes integrated, as I want `goto` as much as the next person. However, getting this user-ready is probably going to require a fair amount of other work (see also, the other issues in this project).

 - [ ] Merge SquidDev/Cobalt#50.
 - [x] Drop our custom version of `load` - this has been handled within the Lua VM for a while now.
 - [ ] Test with some of the most popular programs (well, those which still work on latest CC D:).

**Comment by MCJack123** [comment]
Point # 2 is now complete as of bc8e0908735b3872a3bbcc019e2a13142c8b0915 - it should be checked off now.

**Comment by TChapman500** [comment]
Shouldn't we update to Lua 5.4 instead?  That is the latest version now.

**Comment by SquidDev** [comment]
Eventually, but it's a lot more work.

**Comment by MCJack123** [comment]
With 1.100 on the way and 1.18 just coming out, I think it's time to finally push out Lua 5.2 :)

As for point # 3, why not make the general public (running 1.18) the testers?
