### ISSUE TITLE
Turtle NBT upgrade data are loss when you break turtle

### ISSUE THREAD

**Issue by SirEdvin** [cc-tweaked/CC-Tweaked#847]
### Minecraft Version

1.16.x

### Version

1.97.0

### Details

So, I am trying to store some Upgrade data in NBT, and when I break and place turtle back, everything is vanish. Not sure that this is how it should be.

**Comment by SquidDev** [comment]
> Not sure that this is how it should be.

No, neither.

**Comment by SquidDev** [comment]
I think I'm going to consider this as "working as intended". However, we should look into an alternative API for storing data about the upgrade which _will_ be persisted across breaking/placing.

**Comment by SirEdvin** [comment]
Thanks. If we speak about `use cases`, current usecase is warp point storing. 

My turtle upgrade provide ability to store position points with labels and then warp to them. I cannot save this points to computer file system, so I should store it on nbt data in upgrade.
