### ISSUE TITLE
Make turtle.place() work with glass bottles.

### ISSUE THREAD

**Issue by gtm-nayan** [cc-tweaked/CC-Tweaked#854]
I was trying to make a auto honey harvester using a turtle until I found out that turtle.place() doesn't work with glass bottles. Since dispensers work with glass bottles and turtle.place() is similar to dispensers with buckets, turtles should be able to use them as well.

Perhaps a better way to do this would be to add a turtle.use() method to separate using items such as buckets, glass bottles, animal feed from placing blocks, saplings, seeds etc.

**Comment by fatboychummy** [comment]
Ah, the turtle.use request again. It will be denied, [trust me I've asked](https://github.com/SquidDev-CC/CC-Tweaked/issues/125). 

Although, might I suggest `turtle.dispense()` for buckets and whatnot? `turtle.place` could retain its usage on buckets for backwards compatability, but the turtle would be able to dispense items (armor and everything) like a dispenser. 

Though the above might fall under [Squid's last reply on my issue](https://github.com/SquidDev-CC/CC-Tweaked/issues/125#issuecomment-616205387);
> My stance has always been that this is best served by a peripheral mod, such as plethora. Using arbitrary items is a sufficiently powerful feature that it should be gated behind an upgrade, and I don't want to add such a thing to core CC:T.

**Comment by Wojbie** [comment]
Also one could also code turtle to place dispenser, put bottle in and provide the Redstone signal. While I realize it's not as powerful as what you are suggesting it would make a good fallback you can use now.

**Comment by 698969** [comment]
Well, this issue was mostly about being able to use glass bottles rather than about turtle.use() so I hope implementing it is not off the table.

**Comment by Lupus590** [comment]
> Well, this issue was mostly about being able to use glass bottles rather than about turtle.use() so I hope implementing it is not off the table.

And it does kinda fit, since we can place buckets.
