### ISSUE TITLE
[1.16.5] CraftTweaker Turtle Tools Duplicate Spam

### ISSUE THREAD

**Issue by Flexico** [cc-tweaked/CC-Tweaked#932]
### Minecraft Version

1.16.x

### Version

1.98.2

### Details

This is happening again! It happened before but got fixed, but after I upgraded Project: Red to its beta version this spam started happening again. I'm 99% positive that's the only thing I changed between it not spamming, and then spamming again!

![2021-10-02_11 32 21](https://user-images.githubusercontent.com/5751770/135723884-7e4b4a88-1424-45b5-aeb4-3377bbd7037b.png)

**Comment by Lupus590** [comment]
If updating project red is all you did then it sounds like project red is causing crafttweaker to rerun its scripts, if so then this sounds like a project red issue or a craft tweaker issue.

**Comment by Flexico** [comment]
Hmm, yes, that makes sense!

**Comment by SquidDev** [comment]
I managed to avoid fixing this by just waiting until 1.16.5 is no longer supported D:.
