### ISSUE TITLE
Computers don't always restart on chunk load

### ISSUE THREAD

**Issue by NielsPilgaard** [cc-tweaked/CC-Tweaked#951]
### Minecraft Version

1.16.x

### Version

cc-tweaked-1.16.5-1.98.2

### Details

Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3631

## TL:DR

Computers automatically power off when a chunk unloads.

## What is the issue?

When running a program on a computer or simply booting one up, it would seem like the computers will shut down when the chunk they are located within becomes unloaded or when the server restarts. The expected behavior of the computer is that it saves its current state whenever the game shuts down or the chunk it is within is unloaded. When reloaded, either when the chunk is loaded once more or the server boots up, it should recall its previous state from memory and continue from where it left off. During the time when force chunk loading was cleared on top of whenever the server restarted (On the [official Enigmatica 6 server](https://discord.gg/enigmatica) server I might add), I would notice that all my computers would shut off and would have to be restarted. When noticing this issue, I contacted an admin of the server to which they declared that there is no configuration within the server that would alter the behavior of this feature.

**Comment by SquidDev** [comment]
> The expected behavior of the computer is that it saves its current state whenever the game shuts down or the chunk it is within is unloaded. When reloaded, either when the chunk is loaded once more or the server boots up, it should recall its previous state from memory and continue from where it left off. 

ComputerCraft has never done this. There's an outstanding issue for this (see #535), but it's a chunk of work, and not much has been done on it.

> I would notice that all my computers would shut off and would have to be restarted. 

This is more concerning. I thought we'd fixed all of these bugs a few years ago, but possible later Minecraft versions have had a regression. @PaxiTheAlchemist, I'd appreciate logs if you have them. Not expecting anything interesting, but just in case.

**Comment by PaxiTheAlchemist** [comment]
> ComputerCraft has never done this. There's an outstanding issue for this (see #535), but it's a chunk of work, and so not much has been done on it.

Oh? In my searches to find a solution to booting computers using external non-player methods, I may have stumbled and mixed up that assumption across a forum that referenced what I was referring to, however, if there has never been persistence built into computers then that is fine. I have seen hacky persistence solutions, however it is not in the scope of my use case to which using a startup file in root should be good enough for me.

> This is more concerning. I thought we'd fixed all of these bugs a few years ago, but possible later Minecraft versions have had a regression. @PaxiTheAlchemist, I'd appreciate logs if you have them. Not expecting anything interesting, but just in case.

In game, whenever a chunk would unload while a computer was on, the computer would appear in an inactive state (off/shutdown) when the chunk is reloaded. Basically, it doesnt reboot when the chunk it is located within is loaded once more after being unloaded prior. Reading through forums has told me that computers should at least reboot when their chunk is reloaded?  And also in regards to logs, I experienced this behaviour on a server to which I am unable to acquire them, however whether this aids in finding the solution, even completely new computers that have no edits to their file system with no program running but the shell will be in this inactive state after simply turning them on and leaving and returning to it's chunk. In anycase thank you for the clarification.

**Comment by Seniorendi** [comment]
I had similar issues on my old server.
Sometimes the computers aren't booting. A very rare issue.
But I don't have logs anymore for this server, so this comment is useless. 😅
