### ISSUE TITLE
Mining Turtle tunnel command appears broken

### ISSUE THREAD

**Issue by Flatts3000** [cc-tweaked/CC-Tweaked#952]
### Minecraft Version

1.17.x

### Version

1.98.2

### Details

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/7464076/latest.log)

I have an advanced mining turtle and I'm trying to use the tunnel command. It appears that it refuses to break a block and then when it can't move it errors out of the command. I've tried at positive and negative Y values.

**Comment by SquidDev** [comment]
>  It appears that it refuses to break a block 

Can you run `turtle.dig()` in the Lua REPL and post the output? I'd imagine some block protection is kicking in, and would be useful to see the error.

> it errors out of the command

What error does it give you?

**Comment by Flatts3000** [comment]
> What error does it give you?

- Tunnelling...
- Aborting Tunnel
- Tunnel complete
- Mined 0 items total.

> Can you run `turtle.dig()` in the Lua REPL...
I'll need to do some research to figure out what you mean.

**Comment by Flatts3000** [comment]
The dig() error is "Cannot break protected block"

**Comment by SquidDev** [comment]
That sounds like you've got some block protection mod stopping the turtle breaking blocks.

**Comment by Flatts3000** [comment]
Yep. I downgraded the mod pack (same cc version) and it works now. Contacting the pack creators. Sorry for the bother.

**Comment by SquidDev** [comment]
Good good, glad you've got a fix :)
