### ISSUE TITLE
Blocks Missing Mineable Tag

### ISSUE THREAD

**Issue by WenXin20** [cc-tweaked/CC-Tweaked#953]
### Minecraft Version

1.17.x

### Version

1.98.2

### Details

- CC Tweak's blocks in 1.17 are all missing the block tag `#minecraft:mineable/tool_type`, such as `#minecraft:mineable/pickaxe`. This means the blocks don't currently break quicker with a pickaxe, axe, etc. 
- The block tags `#minecraft:needs_diamond_tool`, `#minecraft:needs_iron_tool`, or `#minecraft:needs_stone_tool` can also be added. This can make it so the lower level tool can't break the defined block.

**Comment by SquidDev** [comment]
Thanks for the report! I'd registered the new block tags, but not really thought about the fact that my blocks might need them. Should be fixed in the next version.

**Comment by WenXin20** [comment]
Cool, sounds good!
