### ISSUE TITLE
NullPointerException on server stop for loaded speaker peripherals

### ISSUE THREAD

**Issue by wieselkatze** [cc-tweaked/CC-Tweaked#956]
### Minecraft Version

1.16.x

### Version

1.98.2

### Details

The following exception happens when stopping a dedicated server with a turtle that has the speaker peripheral attached and is in a currently loaded chunk:

[Link to Gist with stack trace](https://gist.github.com/wieselkatze/7add940fd46dfeba89d3c3230d3da9e7)

The stack trace also contains the mod Performant, this also happened before installing the mod, though.

**Comment by SquidDev** [comment]
Thank you for the report!
