### ISSUE TITLE
Consider changing the recipe for Wired Modem

### ISSUE THREAD

**Issue by cyb0124** [cc-tweaked/CC-Tweaked#961]
The current recipe for Wired Modem (8 stones around 1 redstone) conflicts with the Futura Block from the Chisel mod, which co-exists with CC in many popular modpacks. This causes the Wired Modem uncraftable in the first few versions of these modpacks, until someone finally notices it and report it to modpack authors so that they can fix it manually. Could we change the official recipe here, so that CC can be fully usable in the first release in new modpacks, and that the same fix doesn't have to be repeated by every modpack devs?

Issues I have found:
```
https://github.com/NillerMedDild/Enigmatica6/issues/2910
https://github.com/simibubi/Above-and-Beyond/issues/43
https://github.com/FTBTeam/FTB-Revelation-2/issues/246
https://github.com/DarkPacks/Crackpack-3/issues/121
https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/119
https://github.com/AllTheMods/ATM3-Remix/issues/172
https://github.com/AllTheMods/ATM-6/issues/2316
https://github.com/xJon/The-1.12.2-Pack/issues/67
```

**Comment by SquidDev** [comment]
The wired modem recipe predates Chisel by two years. I'm open to alternative recipe suggestions, but it does feel like this should be an issue on Chisel's end.

**Comment by Ch1216** [comment]
![newrecipe](https://user-images.githubusercontent.com/68875386/144886012-08275331-fb9f-4704-ba9c-18211d1bc4d6.png)

**Comment by Wojbie** [comment]
![obraz](https://user-images.githubusercontent.com/5893536/145093556-2889e187-8c18-456c-ad42-a14db0015a67.png)
IF the recipe will be changed it would make more sense to add CC-only item to it so it no longer can have collision with other vanilla item based recipes.


On other hand i do think this issue should be cross-posted to Chisel repo.
