### ISSUE TITLE
the shell uses `fs.complete(..., ..., false, false)` which should return nothing

### ISSUE THREAD

**Issue by pjalsGit** [cc-tweaked/CC-Tweaked#968]
I'm working on a cloud FS (because of #962) and I noticed that the shell uses `fs.complete(..., ..., false, false)` which shouldn't include anything according to the documentation.

**Comment by SquidDev** [comment]
> When a directory is a possible candidate for completion, two entries are included - one with a trailing slash. `include_dirs` can be set to false to only include those with a trailing slash.

`false`, `false` specifies that no files will be included, and `directory/`s are offered but not a raw `directory`.
