### ISSUE TITLE
Tanks() Method on TinkersConstruct

### ISSUE THREAD

**Issue by k9Frosty** [cc-tweaked/CC-Tweaked#970]
### Minecraft Version

1.16.x

### Version

1.98.2

### Details

"tanks()" method outputting "nill" when in use on a Tinkers Construct(3.1.3.271) seared drain.

**Comment by Lupus590** [comment]
Is there any fluid in the smeltery? I seem to remember that some mods don't show a tank when they don't have fluid.

**Comment by k9Frosty** [comment]
There is, 15 blocks of seared stone.

**Comment by Lupus590** [comment]
What if you wrap the controller, does that show tanks?

**Comment by k9Frosty** [comment]
Okay I got it to work, I guess I just didn't get how it was supposed to work. "peripheral.call("front", tanks)" worked, I was trying to just call tanks after wraping. Thanks for helping Lupus.
