### ISSUE TITLE
NoSuchMethodError In Turtles Causes Server Crash

### ISSUE THREAD

**Issue by KasKatto** [cc-tweaked/CC-Tweaked#972]
### Minecraft Version

1.16.x

### Version

1.99.0

### Details

[crash-2021-11-29_22.04.13-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/7621242/crash-2021-11-29_22.04.13-server.txt)

Just being around a mining turtle seems to cause a crash. World was updated from version 1.98.2. The server is running on Mohist instead of forge, however this wasnt an issue before updating and they worked fine.

**Comment by SquidDev** [comment]
One of your mods is incorrectly bundling the ComputerCraft API - this hasn't been the recommended thing to do for a long time now.

If you've got a link to your modpack download I can probably work out what it is, otherwise I'm afraid you'll have to remove mods until you can isolate what it is.

**Comment by KasKatto** [comment]
i see. My first random guess would be maybe Advanced Peripherals? It was updated as well, so ill see if downgrading that to the last version changes anything. For the record the modpack being used is [Zesty Modpack](https://www.curseforge.com/minecraft/modpacks/zesty-modpack)

**Comment by SquidDev** [comment]
This appears to be an issue with [Supplementaries](https://github.com/MehVahdJukaar/Supplementaries). Downgrading to 0.17.8 should fix things, though worth reporting this on their end - they should _not_ be bundling CC classes with their mod.

**Comment by MehVahdJukaar** [comment]
oh so I read on the docs it was fine to boundle the api. What would be the correct way to do it?

**Comment by SquidDev** [comment]
@MehVahdJukaar We have a Maven repo, so should be possible to use like any other mod - https://github.com/cc-tweaked/CC-Tweaked#using. 

Can you remember where in the docs it mentioned the API should be bundled? That's definitely my fault for not updating it.
