### ISSUE TITLE
Server crash on start

### ISSUE THREAD

**Issue by Brycey92** [cc-tweaked/CC-Tweaked#973]
### Minecraft Version

1.16.x

### Version

1.99.0

### Details

I upgraded from the previous version of CC: Tweaked without resetting my world, and received this crash and stall report:

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/7627982/latest.log)
[crash-2021-11-30_13.30.49-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/7627986/crash-2021-11-30_13.30.49-server.txt)
[crash-2021-11-30_13.31.49-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/7627985/crash-2021-11-30_13.31.49-server.txt)

I'm on a private pack that I can upload somewhere, along with the world file, if that helps debugging.

**Comment by SquidDev** [comment]
See #973. Supplementaries is bundling the CC:T API by mistake - you either need to downgrade CC:T or Supplementaries for the time being.

**Comment by Brycey92** [comment]
Started an issue on their tracker https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues/183

**Comment by Brycey92** [comment]
Ahh, whoops! Closed my new issue on their tracker. Thanks for the update on things!
