### ISSUE TITLE
Crouching while opening an off-hand pocket computer forces you to crouch indefinitely when you stop using it.

### ISSUE THREAD

**Issue by KMorris29** [cc-tweaked/CC-Tweaked#975]
### Minecraft Version

1.16.x

### Version

1.99.0

### Details

When holding a pocket computer in your off-hand, you may want to hold shift while opening it in case you are trying to open it while looking at a chest, a monitor, or what have you. However, while you stop crouching while the pocket computer is open, once you press escape you immediately crouch back down, regardless of if you were still holding shift or not.

More importantly, you REMAIN crouched, even while walking, jumping, or trying and failing to sprint, until you press shift once again.

Ideally, shift-right-clicking while a pocket computer is in your off hand should still stop you from crouching while you are using it, so that you can use it while looking at something like a monitor.

**Comment by SquidDev** [comment]
Thanks for the report! That was a nasty one to track down.
