### ISSUE TITLE
[Crash - 1.16.5] CC-Tweaked crashes server on startup

### ISSUE THREAD

**Issue by p1ut0nium-git** [cc-tweaked/CC-Tweaked#976]
### Minecraft Version

1.16.x

### Version

cc-tweaked-1.16.5-1.99.0

### Details

Crash Report :https://www.toptal.com/developers/hastebin/vofuciliga

**Comment by SquidDev** [comment]
See #973. Supplementaries is bundling the CC:T API by mistake - you either need to downgrade CC:T or Supplementaries for the time being.
