### ISSUE TITLE
Crash when placing computer and disk drive together.

### ISSUE THREAD

**Issue by Iskalldren** [cc-tweaked/CC-Tweaked#980]
### Minecraft Version

1.16.x

### Version

1.99.0

### Details

Basically, a computer block was placed down and I typed the OS startup command but I realised that there was no OS inside so I placed down a disk drive block beside it which then caused the game to crash. The crash apparently was a ticking entity as shown in the crash report. Logs are a bit difficult to obtain but can the bug can be reproduced I think.

[crash-2021-12-04_20.00.37-server (1).txt](https://github.com/cc-tweaked/CC-Tweaked/files/7654176/crash-2021-12-04_20.00.37-server.1.txt)

**Comment by SquidDev** [comment]
See #972. Supplementaries is bundling the CC:T API by mistake - upgrading to their latest version should fix things.
