### ISSUE TITLE
Allow to specify the amount of items to pull or push from an inventory slot, and allow to specify the slot to push to the items in the targeted inventory

### ISSUE THREAD

**Issue by liadinon** [cc-tweaked/CC-Tweaked#984]
Right now we can only specify from which slot we pull the items in a inventory and by default the method will push the full slot to the first empty slot in the targeted inventory. But what if I need only one item from the slot? what if I'm using a special storage unit from a mod and it make a difference to which slot the items are getting pushed?

In the existing version of CC:T we don't have a solution to those problems and I don't think it will be hard to implement those.

**Comment by SquidDev** [comment]
Hrmr, isn't that the `limit` argument to [`pushItems`](https://tweaked.cc/generic_peripheral/inventory.html#v:pushItems). Or am I misunderstanding what you're asking for?
