### ISSUE TITLE
Crash as I click creative tab

### ISSUE THREAD

**Issue by Defalting** [cc-tweaked/CC-Tweaked#989]
### Minecraft Version

1.18.x

### Version

1.99.1

### Details

[latest.log](https://github.com/cc-tweaked/CC-Tweaked/files/7722791/latest.log)
Basically got into a creative world, opened the creative menu, clicked on the CC tab and it immediately crashed.
If it helps, I was also using Optifine, version HD_U_H4, with Sildur's Vibrant Shaders,v1.31 (Extreme-VL)

Also gonna link the crashy report (https://crashy.net/Y7mfCQoyEnxmmpZYPuQU)

**Comment by SquidDev** [comment]
Can you remove optifine and try again?

**Comment by Defalting** [comment]
> Can you remove optifine and try again?

Just did: removing it fixes it. Darn it, wanted to play with some nice shaders...

**Comment by SquidDev** [comment]
Probably worth reporting to them then. Their Forge support is still probably pretty patchy right now.

**Comment by Defalting** [comment]
> Probably worth reporting to them then. Their Forge support is still probably pretty patchy right now.

Ok, I understand. Sorry for the trouble, thank you still.
