### ISSUE TITLE
Failed to find class bytes for dan200.computercraft.shared.command.UserLevel$1

### ISSUE THREAD

**Issue by Ai-Kiwi** [cc-tweaked/CC-Tweaked#991]
### Minecraft Version

1.16.x

### Version

1.99.1

### Details

[crash-2021-12-18_15.02.14-server.txt](https://github.com/cc-tweaked/CC-Tweaked/files/7738543/crash-2021-12-18_15.02.14-server.txt)
whenever I start my server as soon as I join this happens.

**Comment by Ai-Kiwi** [comment]
judging from the fact that it was fixed last time by removing my computer craft folder and the problem started happening after installing an app that wraps peripherals (they are moddded ones) i would say it seems like a problem with mods not booting at the same time or something?

**Comment by Ai-Kiwi** [comment]
Alright i have mangerd to fix the problem the problem was that i had wraped and then started writing to a monitor before the server had started. in in other words I was drawing to a monitor the second the computer started.

**Comment by SquidDev** [comment]
Going to close this as a duplicate as it's the same underlying cause (well, I assume) as #991.

**Comment by Lupus590** [comment]
> Going to close this as a duplicate as it's the same underlying cause (well, I assume) as #972.

Fixed that for you.
