### ISSUE TITLE
Drag and drop feature not functioning

### ISSUE THREAD

**Issue by ShadowzOfTheDark** [cc-tweaked/CC-Tweaked#992]
### Minecraft Version

1.16.x

### Version

1.99.1 & 1.99.0 (Works in 1.98.2)

### Details

The drag and drop feature is not working for me. Whenever I drag and drop a file onto my in-game computer it says it successfully imported the file but the new file is empty. This used to work fine for me in 1.98.2. All these logs are from a fresh minecraft instance and world with no other mods than CC:tweaked. 

(log_computer_errors is set to true for all of these logs)

=======================================================================

1.99.1 Log:
[1_99_1.log](https://github.com/cc-tweaked/CC-Tweaked/files/7738824/1_99_1.log)

=======================================================================

1.99.0 Log:
[1_99_0.log](https://github.com/cc-tweaked/CC-Tweaked/files/7738848/1_99_0.log)

Also a video of what is happening:
https://user-images.githubusercontent.com/57125303/146631293-d9537fb9-a167-42ed-b99c-28979f5b1f74.mp4

=======================================================================

1.98.2 Log (working):
[1_98_2.log](https://github.com/cc-tweaked/CC-Tweaked/files/7738849/1_98_2.log)

Also a video of it working:
https://user-images.githubusercontent.com/57125303/146631243-687dc1dc-974e-4552-a0c3-dc6f952a2e91.mp4

=======================================================================

Only difference I notice in logs is that the versions above 1.98.2 have the following output: "Adding slice from 0 to 426" around the time that I attempt to upload a file.

**Comment by SquidDev** [comment]
Thanks for the report! That was one embarrassing bug :facepalm:
