### ISSUE TITLE
Dropped noisy pocket computer should continue playing audio

### ISSUE THREAD

**Issue by pjalsGit** [cc-tweaked/CC-Tweaked#995]
### Minecraft Version

1.18.x

### Version

https://github.com/cc-tweaked/CC-Tweaked/commit/b048b6666d652dafc4614b086782f956de58d377

### Details

Steps to reproduce:
1. Make a pocket computer play audio
2. Drop pocket computer
3. See bug

**Comment by SquidDev** [comment]
> See bug

Is the least helpful thing you could have typed.

**Comment by Lupus590** [comment]
> Steps to reproduce:
> 
> 1. Make a pocket computer play audio
> 2. Drop pocket computer
> 3. Audio stops, expected it to continue

Fixed that for you.

**Comment by Wojbie** [comment]
I mean aren't Pockets supposed to shut down when dropped by player as feature? Is this even a bug.

**Comment by SquidDev** [comment]
I _think_ the issue (again, not clear because it was a very lazy report) was that they stop playing audio sooner than they shut down, as the speaker peripheral isn't ticked.
