### ISSUE TITLE
API does not provide any methods

### ISSUE THREAD

**Issue by xand490** [cc-tweaked/CC-Tweaked#996]
### Minecraft Version

1.16.x

### Version

1.99.1

### Details

Mining Turtle GUI shows the following

Error running computer
bios.lua:9: attempt to call field 'open'
ComputerCraft may be installed incorrectly

I have attempted reinstalling a fresh download of the jar

List of mods installed
https://devbin.dev/lrdyvLTN

Collection of server logs of the event showing the API not providing any methods
https://devbin.dev/RMtPhfyj

**Comment by Lupus590** [comment]
Related #972 ?

**Comment by SquidDev** [comment]
AFAIK, Supplementaries are no longer bundling the API, so I assume this is another mod. Would you be able to zip up your mods folder and upload it?

**Comment by xand490** [comment]
> AFAIK, Supplementaries are no longer bundling the API, so I assume this is another mod. Would you be able to zip up your mods folder and upload it?

Mod folder on the below link
https://anonfiles.com/tddca02bw0/mods_zip

**Comment by SquidDev** [comment]
```
ᐅ for file in *.jar; if unzip -l $file | grep dan200 2&>1 > /dev/null; echo $file; end; end
cc-tweaked-1.16.5-1.99.1.jar
supplementaries-1.16.5-0.17.11.jar
```

Ahah, this is still supplementaries! You'll want to update to 0.17.12b.
