### ISSUE TITLE
Multishell scrolls the window when the terminal is resized and the cursor is offscreen

### ISSUE THREAD

**Issue by LoganDark** [cc-tweaked/CC-Tweaked#999]
Multishell scrolls the window when the terminal is resized and the cursor is offscreen. This breaks some more advanced drawing techniques (like only redrawing content of the screen that changed) because the screen scrolls unexpectedly.

There are two solutions while multishell has this behavior:
- Always put the cursor at (1, 1) after a render. I do this currently. It means I can't use the cursor inside the program and I have to use some other visual indicator, such as a reverse-video block.
- Always redraw the entire screen after a resize. Hardcoding routines for calculating how the screen changed when resized under multishell is too fragile, especially since it depends on the cursor position. Redrawing the entire screen is the only reasonable option.

The culprit is this block:

https://github.com/cc-tweaked/CC-Tweaked/blob/e558b31b2b0195a210c9a542df07aae1460178f4/src/main/resources/data/computercraft/lua/rom/programs/advanced/multishell.lua#L195-L198

This doesn't seem conducive to anything other than the shell - it's unexpected behavior for the screen contents to move when the terminal resizes. It's useful to keep the shell prompt on-screen in that case, but it's an unexpected implementation detail that can't be disabled by programs. I think the drawbacks outweigh the benefits. :/

Please consider removing it from multishell. IMHO, it would have made more sense in `read`, but CC already forgets offscreen contents by the time you receive a `term_resize` event, so it's not possible to reimplement there.

---

I'd like to note that I've seen the recent announcement post detailing SquidDev's departure from CC:T. That is quite unfortunate, especially on the day that I discovered this issue, and I'm not sure if it's possible to solve this if CC:T is no longer making releases.

I'm posting this bug report regardless just to have.

**Comment by Lupus590** [comment]
You could draw to a buffer and then use that to help you redraw the screen when it resizes.

**Comment by LoganDark** [comment]
> You could draw to a buffer and then use that to help you redraw the screen when it resizes.

I already _use_ buffers for compositing and reconciliation. I have no problem redrawing the entire screen from scratch, I just would prefer not to.

**Comment by SquidDev** [comment]
> IMHO, it would have made more sense in read 

It's relevant for pretty much all non-GUI programs, not just those using `read`. For anything which is printing output to the screen, in makes more sense to see the bottom than the top.

**Comment by LoganDark** [comment]
> > IMHO, it would have made more sense in read
> 
> It's relevant for pretty much all non-GUI programs, not just those using `read`. For anything which is printing output to the screen, in makes more sense to see the bottom than the top.

It does indeed.

> Really, it feel the right thing to do is just handle the `term_resize` event and do a full redraw on that.

That is one of the workarounds to this behavior, yes. However, certain programs like `edit` technically only need to redraw the _bottom_ line of the screen when the terminal is resized to be smaller - since the top-left portion (excluding of course the menu) will stay the same regardless of screen size.

It wouldn't be worth it to implement a behavior like that in `edit`, but it's just an example.

I think behaviors like this should be up to the application. `print`, `read`, etc. should all have it since those are primitives used to build command-line applications, and developers can opt out of them, but stuff like multishell probably shouldn't, because there's no guarantee that the user will only be running command-line applications. GUI libraries suffer when they try to do clever things and get hit by stuff like this.

**Comment by Wojbie** [comment]
> That is one of the workarounds to this behavior, yes.

It is not a workaround. It is expected that a program that is not simple terminal printer (like gui based) that receives `term_resize` event is supposed to redraw all of its contents cause terminal has changed size in undefined way (example: Its on monitor and someone removed/added row of monitors on right side herby increasing length of term object)

**Comment by LoganDark** [comment]
> > That is one of the workarounds to this behavior, yes.
> 
> It is not a workaround. It is expected that a program that is not simple terminal printer (like gui based) that receives `term_resize` event is supposed to redraw all of its contents cause terminal has changed size in undefined way (example: Its on monitor and someone removed/added row of monitors on right side herby increasing length of term object)

The specific behavior I'm referring to is the fact that multishell currently breaks the guarantee that the origin of the terminal resize is always the top-left, i.e. cells within both the old and new size remain the same. Although I am not quite sure if CC ever made such a guarantee, that has traditionally been how it works everywhere outside of multishell.

**Comment by Wojbie** [comment]
It kinda sounds like functional behavior that was never promised to work out that way.

**Comment by LoganDark** [comment]
> It kinda sounds like functional behavior that was never promised to work out that way in any of CC literature.

It's an implementation detail yes, but usually vanilla CC only has one implementation of behavior.

I suppose I would also consider it a resolution of this issue if it were specified in the documentation that `term_resize` events *break all guarantees of what is on the screen and where it is located* since that is in effect what is happening here. Then sure, the correct solution would simply be to invalidate the cache and redraw the entire screen.
